targets:
  $default:
    builders:
      flutter_json_localization_generator|flutter_json_localization:
        enabled: true

builders:
  flutter_json_localization:
    target: ":flutter_json_localization_generator"
    import: "package:flutter_json_localization_generator/builder.dart"
    builder_factories: ["flutterJSONLocalization"]
    build_extensions: {".dart": [".flutter_json_localization.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]